---
title: "Apply variants filters, wecare feb2016"
author: "Alexey Larionov"
output: html_document
---

started: Mar2016
last updated: 01May2016

# start_section

```{r start_section}

# Time stamp
Sys.time()

# Clean-up
rm(list=ls())
graphics.off()

# Set root working folder
library(knitr)

opts_knit$set(root.dir = "/scratch/medgen/scripts/rscripts_05.16")
#setwd("/scratch/medgen/scripts/rscripts_05.16")

#opts_knit$set(root.dir = "C:\\Users\\larion01\\Documents\\GitHub\\R1")
#setwd("C:\\Users\\larion01\\Documents\\GitHub\\R1")

```

# load_and_check_data

```{r load_and_check_data}

load(file="data/s01_read_data_feb2016.RData")
ls()

dim(covar.df)
colnames(covar.df)
str(covar.df)
covar.df[1:5,1:5]

dim(samples.df)
colnames(samples.df)
str(samples.df)
samples.df[1:5,]

dim(vv.df)
colnames(vv.df)
str(vv.df)
vv.df[1:5,1:3]

dim(gt.df)
gt.df[1:5,1:3]

dim(gq.df)
gq.df[1:5,1:3]

dim(dp.df)
dp.df[1:5,1:3]

dim(ad.mx)
ad.mx[1:5,1:3]

dim(ref.mx)
ref.mx[1:5,1:3]

dim(alt.mx)
alt.mx[1:5,1:3]

# Check consistence of rownames
sum(rownames(gt.df) != rownames(vv.df), na.rm=TRUE)

sum(rownames(gt.df) != rownames(gq.df), na.rm=TRUE)
sum(rownames(gt.df) != rownames(dp.df), na.rm=TRUE)
sum(rownames(gt.df) != rownames(ad.mx), na.rm=TRUE)
sum(rownames(gt.df) != rownames(ref.mx), na.rm=TRUE)
sum(rownames(gt.df) != rownames(alt.mx), na.rm=TRUE)

# Check consistence of colnames
sum(substr(colnames(gt.df),0,6) != substr(colnames(gq.df),0,6), na.rm=TRUE)
sum(substr(colnames(gt.df),0,6) != substr(colnames(dp.df),0,6), na.rm=TRUE)
sum(substr(colnames(gt.df),0,6) != substr(colnames(ad.mx),0,6), na.rm=TRUE)
sum(substr(colnames(gt.df),0,6) != substr(colnames(ref.mx),0,6), na.rm=TRUE)
sum(substr(colnames(gt.df),0,6) != substr(colnames(alt.mx),0,6), na.rm=TRUE)

```

# filter_variants

```{r filter_variants}

# Genoptypes NA rate before variants filtering
sum(is.na(gt.df))/(dim(gt.df)[1]*dim(gt.df)[2]) # ~6%

vars.pf <- vv.df$FILTER == "PASS"
sum(vars.pf)

vv.pf.df <- vv.df[vars.pf,]
dim(vv.pf.df)
rm(vv.df)

gt.pf.df <- gt.df[vars.pf,]
dim(gt.pf.df)
rm(gt.df)

gq.pf.df <- gq.df[vars.pf,]
dim(gq.pf.df)
rm(gq.df)

dp.pf.df <- dp.df[vars.pf,]
dim(dp.pf.df)
rm(dp.df)

ad.pf.mx <- ad.mx[vars.pf,]
dim(ad.pf.mx)
rm(ad.mx)

ref.pf.mx <- ref.mx[vars.pf,]
dim(ref.pf.mx)
rm(ref.mx)

alt.pf.mx <- alt.mx[vars.pf,]
dim(alt.pf.mx)
rm(alt.mx)

rm(vars.pf, ad.df, ad.pf.mx)

# Genoptypes NA rate after variants filtering
sum(is.na(gt.pf.df))/(dim(gt.pf.df)[1]*dim(gt.pf.df)[2]) # <1%

```

# save_data

```{r save_data}

save.image(file="data/s02_filter_variants_feb2016.RData")

```

# final_section

```{r final_section}

sessionInfo()
Sys.time()

```

