---
title: "Filter genotypes, wecare feb2016"
author: "Alexey Larionov"
output: html_document
---

started: Mar2016
last updated: 27Apr2016

# start_section

```{r start_section}

# Time stamp
Sys.time()

# Clean-up
rm(list=ls())
graphics.off()

# Set root working folder
library(knitr)

opts_knit$set(root.dir = "/scratch/medgen/scripts/rscripts_05.16")
#setwd("/scratch/medgen/scripts/rscripts_05.16")

#opts_knit$set(root.dir = "C:\\Users\\larion01\\Documents\\GitHub\\R1")
#setwd("C:\\Users\\larion01\\Documents\\GitHub\\R1")

```

# filtering_settings

```{r filtering_settings}

min.dp <- 10
min.gq <- 20

hom.maf.max <- 0.05
het.maf.min <- 0.35

```

# load_and_check_data

```{r load_and_check_data}

load(file="data/s02_filter_variants_feb2016.RData")
ls()

dim(covar.df)
colnames(covar.df)
str(covar.df)
covar.df[1:5,1:5]

dim(demographics.df)
colnames(demographics.df)
str(demographics.df)
demographics.df[1:5,1:5]

dim(samples.df)
colnames(samples.df)
str(samples.df)
samples.df[1:5,]

dim(vv.pf.df)
colnames(vv.pf.df)
str(vv.pf.df)
vv.pf.df[1:5,1:3]

dim(gt.pf.df)
gt.pf.df[1:5,1:3]

dim(gq.pf.df)
gq.pf.df[1:5,1:3]

dim(dp.pf.df)
dp.pf.df[1:5,1:3]

dim(ref.pf.mx)
ref.pf.mx[1:5,1:3]

dim(alt.pf.mx)
alt.pf.mx[1:5,1:3]

# Check consistence of rownames
sum(rownames(gt.pf.df) != rownames(vv.pf.df), na.rm=TRUE)

sum(rownames(gt.pf.df) != rownames(gq.pf.df), na.rm=TRUE)
sum(rownames(gt.pf.df) != rownames(dp.pf.df), na.rm=TRUE)
sum(rownames(gt.pf.df) != rownames(ref.pf.mx), na.rm=TRUE)
sum(rownames(gt.pf.df) != rownames(alt.pf.mx), na.rm=TRUE)

# Check consistence of colnames (sub(".DP","") may be used instead)
sum(substr(colnames(gt.pf.df),0,6) != substr(colnames(gq.pf.df),0,6), na.rm=TRUE)
sum(substr(colnames(gt.pf.df),0,6) != substr(colnames(dp.pf.df),0,6), na.rm=TRUE)
sum(substr(colnames(gt.pf.df),0,6) != substr(colnames(ref.pf.mx),0,6), na.rm=TRUE)
sum(substr(colnames(gt.pf.df),0,6) != substr(colnames(alt.pf.mx),0,6), na.rm=TRUE)

```

# prepare_tables

```{r prepare_tables}

# Reduce data size for development
#gt.pf.df <- gt.pf.df[10000:11000,]
#gq.pf.df <- gq.pf.df[10000:11000,]
#dp.pf.df <- dp.pf.df[10000:11000,]
#ad.pf.df <- ad.pf.df[10000:11000,]

# Converet to matrices
gt.mx <- as.matrix(gt.pf.df)
gq.mx <- as.matrix(gq.pf.df)
dp.mx <- as.matrix(dp.pf.df)
rm(gt.pf.df, gq.pf.df, dp.pf.df)

dim(gt.mx)
gt.mx[1:5,1:5]

dim(gq.mx)
gq.mx[1:5,1:5]

dim(dp.mx)
dp.mx[1:5,1:5]

# Convert ref/alt tables to numeric
ref.alt.rownames <- rownames(ref.pf.mx)
ref.alt.colnames <- colnames(ref.pf.mx)

ref.mx <- matrix(as.numeric(ref.pf.mx),nrow=nrow(ref.pf.mx))
rownames(ref.mx) <- ref.alt.rownames
colnames(ref.mx) <- ref.alt.colnames

dim(ref.mx)
ref.mx[1:5,1:5]

alt.mx <- matrix(as.numeric(alt.pf.mx),nrow=nrow(alt.pf.mx))
rownames(alt.mx) <- ref.alt.rownames
colnames(alt.mx) <- ref.alt.colnames

dim(alt.mx)
alt.mx[1:5,1:5]

rm(ref.alt.rownames, ref.alt.colnames, ref.pf.mx, alt.pf.mx)

# Total num of NAs before genotype filtering
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # <1%

```

# filter_by_gq

```{r filter_by_gq}

NA -> gt.mx[ gq.mx < min.gq ]
rm(gq.mx, min.gq)

# num of NAs after filter
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # ~5%

```

# filter_by_dp

```{r filter_by_dp}

NA -> gt.mx[ dp.mx < min.dp ]
rm(dp.mx, min.dp)

# num of NAs after filter
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # ~7%

```

# prepare_maf_table

```{r prepare_maf_table}

# Sum of ref and alt
ref.alt.sum <- ref.mx + alt.mx

dim(ref.alt.sum)
ref.alt.sum[1:15,1:5]

# Subtract alt from ref
ref.sub.alt <- ref.mx - alt.mx

dim(ref.sub.alt)
ref.sub.alt[1:15,1:5]

# Get minor allele count
ref.alt.mac <- ref.sub.alt
ref.alt.mac[ref.sub.alt == 0] <- ref.mx[ref.sub.alt == 0]
ref.alt.mac[ref.sub.alt < 0] <- ref.mx[ref.sub.alt < 0]
ref.alt.mac[ref.sub.alt > 0] <- alt.mx[ref.sub.alt > 0]

dim(ref.alt.mac)
ref.alt.mac[1:15,1:5]

ref.mx[1:15,1:5]
alt.mx[1:15,1:5]

rm(ref.sub.alt)

# Get minor allele fraction
maf.mx <- ref.alt.mac/ref.alt.sum

dim(maf.mx)
maf.mx[1:15,1:5]

ref.alt.mac[1:15,1:5]
ref.alt.sum[1:15,1:5]

sum(!is.finite(maf.mx))

rm(ref.alt.mac, ref.alt.sum)

```

# filter_by_ad

```{r filter_by_ad}

# num of NAs before filters
sum(is.na(gt.mx))
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # ~7%

# Filter genotype calls with uncertain maf
NA -> gt.mx[ !is.finite(maf.mx) ]

# num of NAs after filter
sum(is.na(gt.mx))
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # ~7%

# Filter homozigous genotype calls
NA -> gt.mx[ gt.mx != 1 & maf.mx > hom.maf.max ]

# num of NAs after filter
sum(is.na(gt.mx))
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # ~7%

# Filter heterozigous genotype calls
NA -> gt.mx[ gt.mx == 1 & maf.mx < het.maf.min ]

# num of NAs after filter
sum(is.na(gt.mx))
sum(is.na(gt.mx))/(dim(gt.mx)[1]*dim(gt.mx)[2]) # ~8%

```

# save_data

```{r save_data}

save.image(file="data/s03_filter_genotypes_feb2016.RData")

```

# final_section

```{r final_section}

sessionInfo()
Sys.time()

```

